spring.application.name=backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres:5432/mycarlogdb
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=https://car-dash.app/login/oauth2/code/google

# CORS ? ?????
app.cors.allowed-origins=https://car-dash.app
app.frontend-url=https://car-dash.app